### ISSUE TITLE
Logging autorisatie en protocollering voor reisdocumenten API gelijktrekken met andere API's

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-Reisdocumenten-bevragen#145]
Met name loggen van het request. Dit wordt nu gelogd naar metadata.requestBody. Voor de overige API's wordt dit gelogd naar metadata.request.body.

Om overzicht te maken over gebruik van alle API's en de operaties daarvan is het ernstig handig wanneer alle API's  het request body type op dezelfde plek in de logging hebben staan.

N.B. ik gebruik daarvoor de logging van de autorisatie en protocollering API, niet de logging van de andere componenten.

**Comment by fsamwel** [comment]
@MelvLee kan hiervoor op de reisdocumenten API de laatste versie van de autorisatie en protocollering proxy worden geïnstalleerd? Of moet daar iets aan worden gedaan om te werken met reisdocumenten?

**Comment by MelvLee** [comment]
> [@MelvLee](https://github.com/MelvLee) kan hiervoor op de reisdocumenten API de laatste versie van de autorisatie en protocollering proxy worden geïnstalleerd? Of moet daar iets aan worden gedaan om te werken met reisdocumenten?

Ja, de laatste versie van de A&P kan worden geïnstalleerd. En nee, er hoeft niets te gebeuren om de A&P werkende te krijgen. Om secured log stream te krijgen moet de ECS__SecuredPath env setting worden geconfigureerd. Ik vermoed dat de versie van A&P die nu voor reisdocumenten is geconfigureerd geen secured log stream ondersteuning heeft
