### ISSUE TITLE
GBA: casus waar kinderen bij ouders in het reisdocument zijn opgenomen.

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-Reisdocumenten-bevragen#52]
**Beschrijf de verbetering**
Voor juni 2012 werden kinderen nog opgenomen in de reisdocumenten van een ouder. Hier moet logica voor komen in vorm van een feature voor het kunnen filteren van deze casussen.
Bij het zoeken op reisdocumentnummer verwacht je maar 1 document, maar het is mogelijk om een reisdocument te raadplegen waar meer records uit de RvIG db kan komen omdat een ouder zijn/haar kind op eigen reisdocument heeft laten opnemen. Nu is het verstandig om dit te filteren met een datum point of no return zodat dit niet mogelijk is.

Daarnaast kan dit probleem ook voorkomen bij zoeken op burgerservicenummer. Het is mogelijk dat een reisdocumentnummer naar boven komt die de bovengenoemde casus kan veroorzaken.

Kortom het is verstandig om een logica te definieren zodat we dit soort historische issues niet krijgen.

**Comment by fsamwel** [comment]
dit kan al enige tijd niet meer. er zijn geen geldige reisdocumenten meer waar kinderen op het reisdocument van de ouder zijn bijgeschreven
