### ISSUE TITLE
pattern voor reisdocumentnummer

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-Reisdocumenten-bevragen#76]
Volgens https://open.overheid.nl/documenten/ronl-0711d56600d10cb3ac40fbaf332178ab3d4b6660/pdf kunnen er alleen hoofdetters en cijfers in een reisdocumentnummer zitten, en moet die altijd exact 9 tekens lang zijn.

In de testdata van de proefomgeving, én in de data in de acceptatieomgeving zitten reisdocumentnummers die hier niet aan voldoen:
- reisdocumentnummers van minder dan 9 tekens lang
- met kleine letters
- met punt (en niet de standaardwaarde 9 punten)
- met spatie(s) (in acceptatie meer dan 2000 reisdocumentnummers met een spatie)
- met komma
- met dakriet (bijv. ì)

@fransrijkers @DannySiebelink komt dit ook in productie voor? Zitter er controles op het reisdocumtnummer bij verwerking in GBA-V?

**Comment by DannySiebelink** [comment]
Nee, BRP-V voert daar geen controles op uit (bij verwerking van de PL)

**Comment by fransrijkers** [comment]
Ik kan me ook echt niet voorstellen dat die rare tekens in productie voorkomen. Het reisdocumentnummer wordt geautomatiseerd overgenomen uit de RAAS/reisdocumentmodule. Heb je in de spreadsheet van de proefomgeving gecheckt of het op beschreven persoonslijsten voorkomt?

**Comment by DannySiebelink** [comment]
https://www.rvig.nl/binaries/rvig/documenten/richtlijnen/2018/09/20/testdataset-persoonslijsten-proefomgevingen-gba-v/Testset+persoonslijsten+proefomgeving+GBA-V.ods @fsamwel

**Comment by fransrijkers** [comment]
In die spreadsheet staan alleen maar paspoortnummers van 9 tekens lang en zo te zien ook alleen gevuld met cijfers en letters.

**Comment by fsamwel** [comment]
deze afwijkende reisdocumentnummers heb ik gevonden in de acceptatieomgeving
