### ISSUE TITLE
inOnderzoek reisdocument op houder

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-Reisdocumenten-bevragen#77]
Als de hele categorie reisdocument in onderzoek staat, is dan ook de houder in onderzoek?
Idem bij reisdocument in onderzoek 123500.

Het mechanisme van in onderzoek zetten is generiek voor alle categorieën, dus je kunt niet echt zeggen wat er bedoeld wordt met het in onderzoek zetten van een hele categorie.
Als de gemeente twijfelt aan de juistheid van gegevens in meer dan 1 gegevensgroep dan is er sowieso geen keuze, dan wordt het automatisch de hele categorie.
Daarom kun je ook niet zeggen dat er een specifieke betekenis is voor een bepaald type reisdocument.
De kans dat een van de rubrieken in de categorie onjuist is, lijkt mij niet erg groot vanwege de omstandigheid dat de categorie meestal automatisch gevuld wordt van de reisdocumentmodule. Ik zou daarom verwachten (maar ik heb daar verder geen informatie over) dat de gemeente de categorie in onderzoek zet als ze eraan twijfelen of de persoon dat reisdocument nog wel heeft.
Het komt inderdaad voor dat de hele categorie reisdocument in onderzoek staat; op dit moment ruim 1800 keer bij ingezetenen.

**Comment by fsamwel** [comment]
@CathyDingemanse heb jij hier al verder onderzoek gedaan bij gemeenten hoe dit gebruikt wordt?

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse heb jij hier al verder onderzoek gedaan bij gemeenten hoe dit gebruikt wordt?

Jazeker, ben ik mee bezig.
