### ISSUE TITLE
wat is een reisdocument met standaardwaarde?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-Reisdocumenten-bevragen#79]
Het reisdocumentnummer kan een standaardwaarde hebben. Wat betekent dit? Is er dan wel echt een reisdocument dat in het bezit is van de persoon?

Idem in geval van soort reisdocument met een standaardwaarde.

**Comment by fransrijkers** [comment]
Het invullen van een standaardwaarde is een algemeen principe in het LO BRP voor situaties waarin een element verplicht ingevuld moet worden. Er is dan een standaardwaarde voorgeschreven om te voorkomen dat iedereen er iets anders van maakt. Er is geen specifieke betekenis per categorie aan gehangen. In feite moet je dit lezen als: er is geen reisdocumentnummer dat aan de regels voldoet. Het zou bijvoorbeeld kunnen zijn dat er bij het invoeren van de gegevens of bij de verhuizing naar een andere gemeente iets fout is gegaan waardoor de waarde in het veld niet maar aan de voorwaarden voldoet. Dan wordt die vervangen door de standaardwaarde.  Je kunt niet zomaar zeggen dat er dan geen reisdocument is. Als er echt geen reisdocument is, dan komt de hele categorie niet voor.

**Comment by fsamwel** [comment]
@CathyDingemanse wat doen we hiermee in de API?

**Comment by MelvLee** [comment]
analoog aan personen. als reisdocumentnummer de standaardwaarde heeft en alleen reisdocumentnummer wordt gevraagd, dan wordt een leeg reisdocument geleverd. TODO: features hiervoor toevoegen bij zoeken met burgerservicenummer

**Comment by fsamwel** [comment]
opgelost met PR #91
